# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: football_app
  username: yuriy
  password: yuriy


test:
  <<: *default
  # database: e2g-rsvp
  # username: yuriy
  # password: yuriy

production:
  <<: *default
  # database: e2g-rsvp
  # username: yuriy
  # password: yuriy
